site_name: AQA PROKA4

theme:
  name: material
  font:
    code: Roboto Mono
#  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.footer
    - header.autohide
    - navigation.expand
    - content.code.copy  # добавляет кнопку "копировать" для кодовых блоков

  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: blue
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - pymdownx.snippets  # поддержка сниппетов
  - pymdownx.highlight  # подсветка синтаксиса кода
  - pymdownx.superfences  # улучшенные блоки кода с поддержкой языков